name: Parentworkflow
on:
  workflow_dispatch:
    inputs: 
       Brand:
          description: 'Brand Type'
          type: choice
          required: true
          options:
            - BRAND 1
            - Brand2
            - Brand3


jobs:
     
     TestJob: 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: |
            response=$(curl -s -o /dev/null -w "%{http_code}" "https://api.github.com/repos/2115-27/hello-world-npm/contents/commits.md?ref=master")
            echo $response is the response
          
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             
#         - run: |
#             echo ${{ github.run_number }}
#             $Brand="${{ inputs.Brand }}"
#             echo "Brand=$Brand"
#             $folder="$Brand"
#             echo "folder=$folder"
#         - name: Zip workspace
#           run: |
           
#            7z a "workspace-${{ github.workflow }}-${{ github.run_number }}.zip" "./"
#            ls
           
#         - name: Upload workspace as artifact
#           if: always()
#           uses: actions/upload-artifact@v3
#           with:
#                name: Workspace of ${{ github.workflow }} RunNumber-${{ github.run_number }}
#                path: workspace-${{ github.workflow }}-${{ github.run_number }}.zip
#                retention-days: 7
               
#         - name: Checkout code
#           uses: actions/checkout@v3
        
#         - run: |
#              echo Brand1 status= ${{ vars.BRAND1 }}
#              sleep 30
             
#         - run: |
#             if [ ${{ inputs.Brand == 'BRAND1' }} ]; then
#               echo checking state of brand1
#               while [ ${{ vars.BRAND1 == 'in_progress' }} ]; do
#                   if [ ${{ vars.BRAND1 == 'completed' }} ]; then
#                      continue
#                   else
#                     echo execution for brand1 is still in progress
#                   fi
#                   echo sleeping before checking again
#                   echo Brand1 status= ${{ vars.BRAND1 }}
#               done  
#             fi  
#         - run: echo Brand1 status= ${{ vars.BRAND1 }}
        
#         - run: |
#             echo test
#             echo ${{ vars.BRAND1 }} is status of BRAND1
#             echo in_progress > myfile.txt 
#             cat myfile.txt
#             gh variable set BRAND1 < myfile.txt
#             echo ${{ vars.BRAND1 }} is status of BRAND1 after updation
#           env:
#             GH_TOKEN: ${{ secrets.REPO }}
     
     ChildJob:
       needs: TestJob
       uses: ./.github/workflows/child2.yml
       with:
         Brand: ${{ inputs.Brand }}
       secrets:
         REPO: ${{ secrets.REPO }}
         
         
         
